#include "vm_data.h"

const char *restrict const ntwt_type_name[] = {
	[NTWT_OP_CODE] = "OP_CODE",
	[NTWT_CHAR]    = "CHAR",
	[NTWT_UINT]    = "UINT",
	[NTWT_INT]     = "INT",
	[NTWT_DOUBLE]  = "DOUBLE",
	[NTWT_STRING]  = "STRING"
};

const int *restrict const ntwt_op_args[] = {
	[NTWT_OP_READ]        = (int []) { 0 },
	[NTWT_OP_END]         = (int []) { 0 },
	[NTWT_OP_CONTEXT]     = (int []) { 1, NTWT_CHAR },
	[NTWT_OP_TEST]        = (int []) { 0 },
	[NTWT_OP_ECHO]        = (int []) { 1, NTWT_STRING },
	[NTWT_OP_AWAKE]       = (int []) { 0 },
	[NTWT_OP_INIT_PRAC]   = (int []) { 1, NTWT_UINT },
	[NTWT_OP_LOAD_PRAC]   = (int []) { 6,
					   NTWT_UINT,
					   NTWT_UINT,
					   NTWT_UINT,
					   NTWT_DOUBLE,
					   NTWT_DOUBLE,
					   NTWT_DOUBLE },
	[NTWT_OP_ACTION]      = (int []) { 2,
					   NTWT_UINT,
					   NTWT_UINT },
	[NTWT_OP_CAN_HAPPEN]  = (int []) { 1,
					   NTWT_DOUBLE },
	[NTWT_OP_STRENGTH]    = (int []) { 1,
					   NTWT_DOUBLE },
	[NTWT_OP_UNSATISFIED] = (int []) { 1,
					   NTWT_DOUBLE },
	[NTWT_OP_RUN]         = (int []) { 0 },
	[NTWT_OP_STRONGER]    = (int []) { 0 },
	[NTWT_OP_SAVE]        = (int []) { 0 },
	[NTWT_OP_INIT_PACK]   = (int []) { 1,
					   NTWT_UINT },
	[NTWT_OP_LOAD_PACK]   = (int []) { 3,
					   NTWT_UINT,
					   NTWT_UINT,
					   NTWT_STRING },
	[NTWT_OP_LOAD_ACTION] = (int []) { 3,
					   NTWT_UINT,
					   NTWT_UINT,
					   NTWT_STRING }
};

const char *restrict const ntwt_op_name[] = {
	[NTWT_OP_READ]        = "READ",
	[NTWT_OP_END]         = "END",
	[NTWT_OP_CONTEXT]     = "CONTEXT",
	[NTWT_OP_TEST]        = "TEST",
	[NTWT_OP_ECHO]        = "ECHO",
	[NTWT_OP_AWAKE]       = "AWAKE",
	[NTWT_OP_INIT_PRAC]   = "INIT_PRAC",
	[NTWT_OP_LOAD_PRAC]   = "LOAD_PRAC",
	[NTWT_OP_ACTION]      = "ACTION",
	[NTWT_OP_CAN_HAPPEN]  = "HAPPEN",
	[NTWT_OP_STRENGTH]    = "STRENGTH",
	[NTWT_OP_UNSATISFIED] = "UNSATISFIED",
	[NTWT_OP_RUN]         = "RUN",
	[NTWT_OP_STRONGER]    = "STRONGER",
	[NTWT_OP_SAVE]        = "SAVE",
	[NTWT_OP_INIT_PACK]   = "INIT_PACK",
	[NTWT_OP_LOAD_PACK]   = "LOAD_PACK",
	[NTWT_OP_LOAD_ACTION] = "LOAD_ACTION"
};
